Repository k1LoW/tbls, pull requests merged in 2023-04, with the labels that each got.

#466 Add a NamingStrategy to map Post.user_id → User.user_id style detected relation
  config/config.go
  config/naming.go
  config/naming_test.go
Labels: enhancement

#467 Add command `tbls ls`
  cmd/ls.go
  go.mod
  go.sum
Labels: enhancement, minor

#468 Fix CI
  .github/workflows/tagpr.yml
Labels: bug
