Repository k1LoW/tbls, pull requests merged in 2023-10, with the labels that each got.

#510 Add an arm64 architecture variant of the Linux build
  .github/workflows/release-test.yml
  .goreleaser/linux.yml
Labels: enhancement, minor

#517 feat:requireViewpoints
  README.md
  config/lint.go
  config/lint_test.go
Labels: enhancement, minor

#518 `coverage` command support loading schema.json
  cmd/coverage.go
  cmd/ls.go
Labels: enhancement

#520 Bump up go and pkg version
  .github/workflows/ci.yml
  .github/workflows/tagpr.yml
  go.mod
  go.sum
Labels: minor

#532 feat:refer viewpoints from tables
  .golangci.yml
  output/md/md.go
  output/md/md_test.go
  output/md/templates/table.md.tmpl
  schema/schema.go
  schema/schema_test.go
  testdata/md_template_test_a.md.golden
  testdata/md_test_a.md.first_para.golden
  testdata/md_test_a.md.golden
  testdata/md_test_a.md.mermaid.golden
  testdata/templates/table.md.tmpl
Labels: enhancement, minor, breaking-change
