Repository k1LoW/tbls, pull requests merged in 2023-06, with the labels that each got.

#479 Fix for when Postgres search path is empty
  drivers/postgres/postgres.go
Labels: bug

#487 Support filtering by column labels
  config/config.go
  sample/viewpoints/README.md
  sample/viewpoints/viewpoint-3.md
  sample/viewpoints/viewpoint-3.svg
  schema/filter.go
  testdata/test_tbls_viewpoints.yml
Labels: minor, breaking-change

#489 Fix parsing foreign key constraints
  drivers/mysql/mysql.go
  drivers/postgres/postgres.go
  drivers/postgres/postgres_test.go
  drivers/sqlite/sqlite.go
  sample/adjust/public.posts.md
  sample/adjust/public.posts.svg
  sample/adjust/public.users.svg
  sample/adjust/schema.json
  sample/adjust/schema.svg
  sample/postgres/public.posts.md
  sample/postgres/public.posts.svg
  sample/postgres/public.users.svg
  sample/postgres/schema.json
  sample/postgres/schema.svg
  testdata/ddl/postgres.sql
Labels: bug

#490 Fix schema.Schema.NormalizeTableName
  schema/schema.go
  schema/schema_test.go
Labels: bug

#493 Support grouping tables in viewpoints
  Makefile
  config/config.go
  config/viewpoints.go
  go.mod
  go.sum
  output/dot/dot.go
  output/dot/dot_test.go
  output/dot/templates/schema.dot.tmpl
  output/gviz/gviz.go
  output/md/md.go
  output/md/md_test.go
  output/md/templates/viewpoint.md.tmpl
  sample/viewpoints/schema.json
  sample/viewpoints/viewpoint-0.svg
  sample/viewpoints/viewpoint-1.svg
  sample/viewpoints/viewpoint-2.md
  sample/viewpoints/viewpoint-2.svg
  sample/viewpoints/viewpoint-3.svg
  schema/filter.go
  schema/json.go
  schema/schema.go
  testdata/dot_template_test_schema.dot.golden
  testdata/dot_test_viewpoint_0.dot.golden
  testdata/dot_test_viewpoint_1.dot.golden
  testdata/dot_test_viewpoint_2.dot.golden
  testdata/dot_test_viewpoint_3.dot.golden
  testdata/json_output_schema.golden
  testdata/md_test_viewpoint-2.md.golden
  testdata/test_tbls_viewpoints.yml
  testdata/yaml_output_schema.golden
  testutil/schema.go
Labels: enhancement, minor

#495 Support `--dsn` option for external subcommands
  cmd/root.go
Labels: enhancement

#497 Use schema.json for subcommand
  cmd/root.go
Labels: minor, breaking-change
