Repository k1LoW/tbls, pull requests merged in 2025-03, with the labels that each got.

#663 chore(deps): update dependencies (go-yaml)
  go.mod
  go.sum
  scripts/jsonschema/go.mod
  scripts/jsonschema/go.sum
  testdata/yaml_output_schema.golden
Labels: minor, breaking-change

#666 Add support for '.yaml' extension to default configuration
  config/config.go
  config/config_test.go
  testdata/config/.tbls.yaml
  testdata/config/tbls.yaml
Labels: enhancement

#668 nit: Fix typo
  config/config.go
  output/dot/dot.go
  output/md/md.go
  schema/filter.go
Labels: bug
